version: "3"
services:
  hub:
    image: seleniarm/hub:4.1.3-20220331
    ports:
      - "4444:4444"
  chrome:
    image: seleniarm/node-chromium:4.1.3-20220331
    shm_size: '2g'        
    depends_on:
      - hub
    environment:
      - SE_EVENT_BUS_HOST=hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
  firefox:
    shm_size: '2g'   
    image: seleniarm/node-firefox:4.1.3-20220331
    depends_on:
      - hub
    environment:
      - SE_EVENT_BUS_HOST=hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
  search-module:
      image: selenium-docker
      depends_on:
        - chrome
        - firefox
      environment:
        - BROWSER=firefox
        - HUB_HOST=hub
        - MODULE=search-module.xml
      volumes:
        - ./search-result:/usr/share/seleniumdocker/test-output 
  book-flight-module:
      image: selenium-docker
      depends_on:
        - chrome
        - firefox
      environment:
        - BROWSER=chrome
        - HUB_HOST=hub
        - MODULE=book-flight-module.xml
      volumes:
        - ./search-result:/usr/share/seleniumdocker/test-output 
